service: wwwsqldesigner

custom:
  stage: ${opt:stage, 'dev'}
  storage:
    bucket: ${env:STORAGE_S3_BUCKET}
    prefix: ${env:STORAGE_S3_PREFIX, 'wwwsqldesigner/'}
  statics:
    bucket: ${env:STATICS_S3_BUCKET}
  cf:
    customDomain: ${env:CF_DOMAIN}
    certificateArn: ${env:CF_CERT_ARN}

provider:
  name: aws
  runtime: python3.7
  environment:
    STORAGE_S3_BUCKET: ${self:custom.storage.bucket}
    STORAGE_S3_PREFIX: ${self:custom.storage.prefix}
  iamRoleStatements:
    - Effect: Allow
      Action: [ 's3:ListBucket' ]
      Resource: arn:aws:s3:::${self:custom.storage.bucket}
    - Effect: Allow
      Action: [ 's3:*' ]
      Resource: arn:aws:s3:::${self:custom.storage.bucket}/${self:custom.storage.prefix}*

package:
  excludeDevDependencies: false
  exclude:
    - "**/*"
    - "!src/*.py"

functions:
  backend:
    handler: src.handler.backend
    events:
      - http:
          path: backend/s3-lambda
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                action: true
                keyword: true
      - http:
          path: backend/s3-lambda
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                action: true
                keyword: false
                database: false

resources:
  ${file(serverless-resources.yml)}
